//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminActivityLog
    {
        public int LogID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string Action { get; set; }
        public string TargetTable { get; set; }
        public Nullable<int> TargetID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
