//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    
    public partial class AIAnalysisRun
    {
        public long RunID { get; set; }
        public string RunType { get; set; }
        public string ModelName { get; set; }
        public string InputJson { get; set; }
        public string OutputJson { get; set; }
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}

