//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    
    public partial class AreaCluster
    {
        public long AreaClusterID { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string ListingType { get; set; }
        public string PropertyType { get; set; }
        public int ClusterNo { get; set; }
        public string ClusterLabel { get; set; }
        public Nullable<decimal> MedianPricePerM2 { get; set; }
        public Nullable<decimal> AverageArea { get; set; }
        public int ListingCount { get; set; }
        public string ModelName { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}

