//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public int ProductID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public string ContractType { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User1 { get; set; }
    }
}
