//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    
    public partial class PricePrediction
    {
        public long PredictionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Ward { get; set; }
        public string Type { get; set; }
        public string ListingType { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<byte> Bedrooms { get; set; }
        public Nullable<byte> Bathrooms { get; set; }
        public decimal PredictedPrice { get; set; }
        public Nullable<decimal> LowPrice { get; set; }
        public Nullable<decimal> HighPrice { get; set; }
        public string ModelName { get; set; }
        public Nullable<decimal> ConfidenceScore { get; set; }
        public string FeatureImportanceJson { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}

