//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_BDS.Models
{
    using System;
    
    public partial class RawListing
    {
        public long RawListingID { get; set; }
        public string Source { get; set; }
        public string SourceUrl { get; set; }
        public string RawTitle { get; set; }
        public string RawPrice { get; set; }
        public string RawArea { get; set; }
        public string RawAddress { get; set; }
        public string RawJson { get; set; }
        public System.DateTime CrawledAt { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}

